### ISSUE TITLE
start.sh usage is unclear

### ISSUE THREAD

**Issue by andreicon** [ac-mercury/mercuryiss-kali#2]
Although the readme in this repo provides information to run the container, it is incomplete.

Running the command with missing parameters should produce a usage example, such as

`./start.sh username /path/to/data /path/to/scripts /path/to/installers`

**Comment by ac-mercury** [comment]
I've updated start.sh and the README.md

**Comment by andreicon** [comment]
you should also add `set -e` at the beginning to keep it from reaching `docker run` if `docker build` fails
